### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by takeyamayuki** [zhan-xu/MoRig#2]
Thanks for the great project.

After following the README and building the environment, I ran it and got the following error.

```sh
(morig) yonelab@yonePC:~/workspace/MoRig$ python -u training/train_rig.py --arch="jointnet_motion" -e --resume ="checkpoints/jointnet_motion/model_best.pth.tar" --train_folder="home/yonelab/workspace/MoRig/ModelsResources/train/" --val_folder="home/yonelab/workspace/MoRig/ModelsResources/val/" --test_folder="home/yonelab/workspace/MoRig/ModelsResources/test/" --output_folder="results/our_results"
Namespace(aggr_method='attn', arch='jointnet_motion', checkpoint='checkpoints/test', epochs=120, evaluate=True, gamma=0.2, logdir='logs/test', lr=0.0005, motion_dim=32, num_keyframes=5, output_folder='results/our_results', resume='=checkpoints/jointnet_motion/model_best.pth.tar', schedule=[40, 80], start_epoch=0, test_batch=2, test_folder='home/yonelab/workspace/MoRig/ModelsResources/test/', train_batch=2, train_folder='home/yonelab/workspace/MoRig/ModelsResources/train/', val_folder='home/yonelab/workspace/MoRig/ModelsResources/val/', weight_decay=0.0001)
=> no checkpoint found at '=checkpoints/jointnet_motion/model_best.pth.tar'
    Total params: 7.88M
Processing...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "training/train_rig.py", line 294, in <module>
    main(parser.parse_args())
  File "training/train_rig.py", line 103, in main
    train_loader = DataLoader(RigDataset(root=args.train_folder), batch_size=args.train_batch, shuffle=True, follow_batch=['joints'])
  File "./datasets/dataset_rig.py", line 13, in __init__
    super(RigDataset, self).__init__(root)
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 56, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 87, in __init__
    self._process()
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 170, in _process
    self.process()
  File "./datasets/dataset_rig.py", line 139, in process
    data, slices = self.collate(data_list)
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 112, in collate
    data_list[0].__class__,
IndexError: list index out of range
```

And here is my environment
Ubuntu20.04, Python 3.7.13

How can I deal with this?
Thank you in advance.

**Comment by takeyamayuki** [comment]
I have corrected the following, but got another error.

```sh
(morig) yonelab@yonePC:~/workspace/MoRig$ python -u training/train_rig.py --arch="jointnet_motion" -e --resume="checkpoints/jointnet_motion/model_best.pth.tar" --train_folder="ModelsResources/train/" --val_folder="ModelsResources/val/" --test_folder="ModelsResources/test/" --output_folder="results/our_results"
Namespace(aggr_method='attn', arch='jointnet_motion', checkpoint='checkpoints/test', epochs=120, evaluate=True, gamma=0.2, logdir='logs/test', lr=0.0005, motion_dim=32, num_keyframes=5, output_folder='results/our_results', resume='checkpoints/jointnet_motion/model_best.pth.tar', schedule=[40, 80], start_epoch=0, test_batch=2, test_folder='ModelsResources/test/', train_batch=2, train_folder='ModelsResources/train/', val_folder='ModelsResources/val/', weight_decay=0.0001)
=> loading checkpoint 'checkpoints/jointnet_motion/model_best.pth.tar'
=> loaded checkpoint 'checkpoints/jointnet_motion/model_best.pth.tar' (epoch 108)
    Total params: 7.88M
Processing...
  0%|                                                                                                          | 0/2163 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "training/train_rig.py", line 294, in <module>
    main(parser.parse_args())
  File "training/train_rig.py", line 103, in main
    train_loader = DataLoader(RigDataset(root=args.train_folder), batch_size=args.train_batch, shuffle=True, follow_batch=['joints'])
  File "./datasets/dataset_rig.py", line 13, in __init__
    super(RigDataset, self).__init__(root)
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 56, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 87, in __init__
    self._process()
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 170, in _process
    self.process()
  File "./datasets/dataset_rig.py", line 83, in process
    v_traj = np.load(vtx_filename)
  File "/home/yonelab/anaconda3/envs/morig/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'ModelsResources/train/raw/ModelsResources/train/540_vtx_traj.npy'
```
but sorry, the npy file did not exist. I'll try a few more things.

I'll close this issue now that it's resolved for now.
